### ISSUE TITLE
V3 breaking change: Remove managed_dependency_enabled property from FunctionLoadRequest

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-language-worker-protobuf#34]
We are creating a new message for the Host to tell the worker to Initialize the function app.
For now, it will include two properties: function app root, and managed dependency enable option.

As a result, we will no longer need the managed_dependency_enabled property in FunctionLoadRequest--we need to remove this property once all workers start using this new message.

**Comment by liliankasem** [comment]
Tracking this in a new issue to consolidate
